trigger: none

stages:
    - stage: Alpha
      displayName: Alpha
      dependsOn: []
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

      jobs:
          - deployment: BuildAndPublishExtension
            environment: alpha
            displayName: Build and Deploy Alpha
            pool:
                vmImage: 'ubuntu-latest'
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/build-template.yml
                              parameters:
                                  version: alpha

          - job: SmokeTest
            displayName: Test Alpha Build
            dependsOn: BuildAndPublishExtension
            strategy:
                matrix:
                    ubuntu:
                        image: 'ubuntu-latest'
            pool:
                vmImage: $(image)

            steps:
                - template: templates/smoke-test-template.yml
                  parameters:
                      version: alpha
                      platform: $(image)

    - stage: Beta
      displayName: Beta
      dependsOn: Alpha

      jobs:
          - deployment: PromoteExtension
            environment: beta
            displayName: Promote to Beta
            pool:
                vmImage: 'ubuntu-latest'
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/build-template.yml
                              parameters:
                                  version: beta

    - stage: Hotfix
      displayName: Hotfix
      dependsOn: []
      condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')

      jobs:
          - deployment: BuildAndPublishExtension
            environment: hotfix
            displayName: Promote to Hotfix
            pool:
                vmImage: 'ubuntu-latest'
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/build-template.yml
                              parameters:
                                  version: hotfix

          - job: SmokeTest
            displayName: Test Hotfix Build
            dependsOn: BuildAndPublishExtension
            strategy:
                matrix:
                    ubuntu:
                        image: 'ubuntu-latest'
            pool:
                vmImage: $(image)

            steps:
                - template: templates/smoke-test-template.yml
                  parameters:
                      version: hotfix
                      platform: $(image)

    - stage: Prod
      displayName: Prod
      dependsOn:
          - Beta
          - Hotfix
      condition: or(succeeded('Beta'),succeeded('Hotfix'))

      jobs:
          - deployment: PromoteExtension
            environment: prod
            displayName: Promote to Prod
            pool:
                vmImage: 'ubuntu-latest'
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/build-template.yml
                              parameters:
                                  version: latest
