# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish sfpowerkit to NPM

on: 
  workflow_call:
    inputs: 
      version:
        description: 'Version of sfpowerkit to build'
        required: true
        default: alpha
        type: string
      package_version:
        description: 'Package version number from package.json'
        required: true
        type: string
        
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - name: npm install
        if:  ${{ github.event.inputs.version }} == alpha || ${{ github.event.inputs.version }} == hotfix || ${{ github.event.inputs.version }} == review
        run: npm install
      
      - name: publish sfpowerkit
        if: ${{ github.event.inputs.version }} == alpha || ${{ github.event.inputs.version }} == hotfix
        run: npm publish --tag ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Promote Package
        if: ${{ github.event.inputs.version }} == beta || ${{ github.event.inputs.version }} == latest
        run: |
            inputs.PKG_VERSION=$(jq -r ".version" package.json)
            npm dist-tag add sfpowerkit@${{ github.event.inputs.package_version }} ${{ github.event.inputs.version }}
