# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and Publish sfpowerkit

on: 
  workflow_dispatch:
    inputs: 
      version:
        description: 'Version of sfpowerkit to build'
        required: true
        default: alpha
      PKG_VERSION:
        description: Package version number
        required: false

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: update build number
        if: inputs.version == alpha || inputs.version == hotfix
        run: |
            inputs.PKG_VERSION=$(jq -r ".version" package.json)
            echo "##vso[build.updatebuildnumber]inputs.PKG_VERSION"
      
      - name: npm install
        if: inputs.version == alpha || inputs.version == hotfix || inputs.version == review
        run: npm install
      
      - name: publish sfpowerkit
        run: npm publish --tag 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Promote Package
        if: inputs.version == beta || inputs.version == latest
        run: |
            inputs.PKG_VERSION=$(jq -r ".version" package.json)
            npm dist-tag add sfpowerkit@inputs.PKG_VERSION inputs.version
      
