name: Publish 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: get version number
        id: getversion
        run: echo "::set-output name=version_number::$(jq -r ".version" package.json)"

      - name: Print VN
        run: echo ${{steps.getversion.outputs.version_number}}
