name: Publish 

on:
  workflow_dispatch:

jobs:

  alpha_build_deploy:
    uses: ./.github/workflows/npm-publish-template.yml
    if: ${{ github.ref }} == 'refs/heads/main'
    with:
        version: alpha
        
  alpha_smoke_test:
    uses: ./.github/workflows/review-smoke-test.yml
    needs: alpha_build_deploy
    if: ${{ github.ref }} == 'refs/heads/main'
        
  beta:
    runs-on: ubuntu-latest
    needs: 
      - alpha_build_deploy
      - alpha_smoke_test
    steps:
      - uses: actions/checkout@v3
        
      - uses: ./.github/workflows/npm-publish-template.yml
        name: Promote to beta
        with: 
          version: beta
          
  hotfix:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/hotfix/'
    steps:
      - uses: actions/checkout@v3
        
      - uses: ./.github/workflows/npm-publish-template.yml
        name: Promote to Hotfix
        with: 
          version: hotfix
  
      - uses: ./.github/workflows/review-smoke-test.yml
        name: smoke test hotfix
        
  prod:
    runs-on: ubuntu-latest
    needs: 
      - beta
      - hotfix
    steps:
      - uses: actions/checkout@v3
        
      - uses: ./.github/workflows/npm-publish-template.yml
        name: Promote to prod
        with: 
          version: latest
    
