name: Format

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/*'
    branches: 
     - main
     - hotfix/*

jobs:
     format:
         runs-on: ubuntu-latest
         steps:
          - uses: actions/checkout@v2
            with:
             ref: ${{ github.head_ref }}
          - uses: actions/setup-node@v2
            with:
             node-version: "14.x"
          - run: npm run format
          - name: Commit changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: 'chore(prettier): Apply formatting changes'
              branch: ${{ github.head_ref }}

